name: SSH Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: SSH into EC2 instance and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.108.155.90 << 'EOF'
        
        # Check if swap exists, if not create it
        if [ $(swapon --show | wc -l) -eq 0 ]; then
          echo "Creating 2GB swap file..."
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
          echo "Swap created successfully"
        fi
        
        cd /home/ubuntu/trackRoutePro-Admin
        
        # Reset any local changes
        git reset --hard
        
        # Pull latest changes
        git pull origin main
        
        # Stop PM2 apps to free up memory
        pm2 stop all
        
        # IMPORTANT: Clean install without sudo and include optional dependencies
        rm -rf node_modules package-lock.json
        npm cache clean --force
        npm install --include=optional
        
        # Build with increased memory
        NODE_OPTIONS="--max-old-space-size=1536" npm run build
        
        # Restart PM2 apps
        pm2 restart all
        
        # Restart Nginx
        sudo systemctl restart nginx
        sudo systemctl status nginx
        
        echo "Deployment completed successfully"
        free -h
        EOF
